routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('accounts', 'AccountController');
Route::resource('accounts/news', 'NewsController');

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
/*Route::get('/accounts', function () {
    return view::make('layout');
});*/

app/Account.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    protected $fillable = [
        'first_name',
        'created_at',
        'last_name',
        'email',
        'city',
        'country',
        'job_title',
        'job_text' ,
        'blogimage1',
        'blogimage2',
        'avatarlink',
        'presentation'     
    ];
}

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $fillable = [
        'id',
        'author',
        'title1',
        'title2',
        'text1',
        'text2',
        'img1',
        'img2'   
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends \TCG\Voyager\Models\User
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Account;
use App\News;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $accounts = Account::all();
        $news = News::all();

        return view('accounts.index', compact('accounts','news' ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view ('accounts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name'=>'required',
            'last_name'=>'required',
            'email'=>'required'
        ]);

        $account = new Account([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'email' => $request->get('email'),
            'job_title' => $request->get('job_title'),
            'job_text' => $request->get('job_text'),
            'city' => $request->get('city'),
            'country' => $request->get('country')
        ]);
        $account->save();
        return redirect('/accounts')->with('success', 'account saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $account = Account::find($id);
        return view('accounts.show', compact('account'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $account = Account::find($id);
        return view('accounts.edit', compact('account'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'first_name'=>'required',
            'last_name'=>'required',
            'email'=>'required'
        ]);

        $account = Account::find($id);
        $account->first_name =  $request->get('first_name');
        $account->last_name = $request->get('last_name');
        $account->email = $request->get('email');
        $account->job_title = $request->get('job_title');
        $account->job_text = $request->get('job_text');
        $account->city = $request->get('city');
        $account->country = $request->get('country');
        $account->save();

        return redirect('/accounts')->with('success', 'account updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $account = Account::find($id);
        $account->delete();

        return redirect('/accounts')->with('success', 'account deleted!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Account;
use App\News;

class NewsController extends Controller
{
    public function show($id)
    {
        $news = News::find($id);
        return view('news.show', compact('news'));
    }

}

resources/views/accounts/create.blade.php
<!--<html>
<body>
@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a contact</h1>
  <div>
  <h2> hELOOOOOOOOOOOOOOOOOOOO</h2>
      <form method="post" action="{{ route('accounts.store') }}">
          @csrf
          <div class="form-group">    
              <label for="first_name">First Name:</label>
              <input type="text" class="form-control" name="first_name"/>
          </div>

          <div class="form-group">
              <label for="last_name">Last Name:</label>
              <input type="text" class="form-control" name="last_name"/>
          </div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="city">City:</label>
              <input type="text" class="form-control" name="city"/>
          </div>
          <div class="form-group">
              <label for="country">Country:</label>
              <input type="text" class="form-control" name="country"/>
          </div>
          <div class="form-group">
              <label for="job_title">Job Title:</label>
              <input type="text" class="form-control" name="job_title"/>
          </div>
          <div class="form-group">
              <label for="job_text">Job Description:</label>
              <input type="text" class="form-control" name="job_text"/>
          </div>                           
          <button type="submit" class="btn btn-primary-outline">Add contact</button>
      </form>
  </div>
</div>
</div>
@endsection
</body>
</html>-->
<html>
<header>
<link >
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/accounts">
    <img src="https://istartblogging.com/wp-content/uploads/2016/03/absolut-logo-design-typography-300x62.png" class="d-inline-block align-top" alt="">
  </a>
</nav>
</header>
<body>
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a Blog</h1>
  <div>
      <form method="post" action="{{ route('accounts.store') }}">
          @csrf
          <div class="form-group">    
              <label for="first_name">First Name:</label>
              <input type="text" class="form-control" name="first_name"/>
          </div>

          <div class="form-group">
              <label for="last_name">Last Name:</label>
              <input type="text" class="form-control" name="last_name"/>
          </div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="city">City:</label>
              <input type="text" class="form-control" name="city"/>
          </div>
          <div class="form-group">
              <label for="country">Country:</label>
              <input type="text" class="form-control" name="country"/>
          </div>
          <div class="form-group">
              <label for="job_title">Job Title:</label>
              <input type="text" class="form-control" name="job_title"/>
          </div>
          <div class="form-group">
              <label for="job_text">Job Description:</label>
              <input type="text" class="form-control" name="job_text"/>
          </div>                           
          <button type="submit" class="btn btn-primary-outline ">Add contact</button>
      </form>
  </div>
</div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

resources/views/accounts/edit.blade.php
<html>
<header>
<link >
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/accounts">
    <img src="https://istartblogging.com/wp-content/uploads/2016/03/absolut-logo-design-typography-300x62.png" class="d-inline-block align-top" alt="">
  </a>
</nav>
</header>
<body>
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Blog</h1>
  <div>
      <form method="post" action="{{ route('accounts.update', $account->id) }}">
      @method('PATCH') 
            @csrf
          <div class="form-group">    
              <label for="first_name">First Name:</label>
              <input type="text" class="form-control" name="first_name" value="{{$account->first_name}}"/>
          </div>

          <div class="form-group">
              <label for="last_name">Last Name:</label>
              <input type="text" class="form-control" name="last_name" value="{{$account->last_name}}"/>
          </div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email" value="{{$account->email}}"/>
          </div>
          <div class="form-group">
              <label for="city">City:</label>
              <input type="text" class="form-control" name="city" value="{{$account->city}}"/>
          </div>
          <div class="form-group">
              <label for="country">Country:</label>
              <input type="text" class="form-control" name="country" value="{{$account->country}}"/>
          </div>
          <div class="form-group">
              <label for="job_title">Job Title:</label>
              <input type="text" class="form-control" name="job_title" value="{{$account->job_title}}"/>
          </div>
          <div class="form-group">
              <label for="job_text">Job Description:</label>
              <input type="text" class="form-control" name="job_text" value="{{$account->job_text}}"/>
          </div>                           
          <button type="submit" class="btn btn-primary-outline ">Save </button>
      </form>
  </div>
</div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

resources/views/accounts/index.blade.php
<html>
<header>
<link rel="stylesheet" type="text/css" href="/css/main.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
<link rel="stylesheet" href="https://use.typekit.net/iul5qke.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/accounts">
            <img src="https://istartblogging.com/wp-content/uploads/2016/03/absolut-logo-design-typography-300x62.png" class="d-inline-block align-top" alt="">
          </a>
    <form class="form-inline filter-bar">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>  
      <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">News</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Blogs</a>
            </li>
            <li class="nav-item" >
              <a class="nav-link" href="/admin">A.P.</a>
            </li>
          </ul>
</nav>
</header>
<body>

<div class="image-background-start">

</div>
<div class="container">
<!--sometext start-->
<div class="row intro-card">
  <div class="col-4">
    <h1 class="intro-card-title"><i class="fab fa-airbnb"></i>My blog</h1>
  </div>
  <div class="col-6 offset-1">
    <p class="intro-card-text">
    A blog (a truncation of "weblog")[1] is a discussion or informational website published on the World Wide Web consisting of discrete, often informal diary-style text entries (posts). Posts are typically displayed in reverse chronological order, so that the most recent post appears first, at the top of the web page. Until 2009, blogs were usually the work of a single individual,[citation needed] occasionally of a small group, and often covered a single subject or topic. In the 2010s, "multi-author blogs" (MABs) emerged, featuring the writing of multiple authors and sometimes professionally edited. MABs from newspapers, other media outlets, universities, think tanks, advocacy groups, and similar institutions account for an increasing quantity of blog traffic. The rise of Twitter and other "microblogging" systems helps integrate MABs and single-author blogs into the news media. Blog can also be used as a verb, meaning to maintain or add content to a blog.
    </p>
  </div> 
</div>
<!--some text finish-->
<div class="row">
@section('main')
@foreach($accounts as $account)
            <div class="col-10">
                <div class="card card-blog">
                    <div class="row">
                      <div class="col-4">
                    <img class="card-blog-img" src="{{$account-> avatarlink}}"   />
                  </div>
                    <div class="col-5">
                      <div class="card-blog-body">
                        <h2 class="card-blog-name">{{$account->first_name}}    {{$account->last_name}}</h2>
                        <h5>Job: {{$account->job_title}}</h5>
                        <h5>Email : {{$account->email}}</h5>
                        <h5>City : {{$account->city}} </h5>
                        <h5>Country: {{$account->country}} </h5>
                        <p class="card-blog-smalltext">Added at :{{$account->created_at}}</p>
                        <form action="{{route('accounts.show', $account->id)}}" method="GET">
                        <button class="btn btn-warning" type="submit">Read blog </button>
                      </form>
                        </div>
                      </div>
                      <div class="col-2">
                        <label class="card-blog-star">
                          <i class="fas fa-star"></i>
                        </label>
                      </div>
                    </div>
                </div>
              </div>
@endforeach
</div>
<!-- news cases-->
</div>
<div class="container">
   <!--sometext start-->
<div class="row intro-card">
  <div class="col-6 offset-1">
    <p class="intro-card-text">
    News is information about current events. This may be provided through many different media: word of mouth, printing, postal systems, broadcasting, electronic communication, or through the testimony of observers and witnesses to events.
    Common topics for news reports include war, government, politics, education, health, the environment, economy, business, fashion, and entertainment, as well as athletic events, quirky or unusual events. Government proclamations, concerning royal ceremonies, laws, taxes, public health, and criminals, have been dubbed news since ancient times. Humans exhibit a nearly universal desire to learn and share news, which they satisfy by talking to each other and sharing information. Technological and social developments, often driven by government communication and espionage networks, have increased the speed with which news can spread, as well as influenced its content. The genre of news as we know it today is closely associated with the newspaper, which originated in China as a court bulletin and spread, with paper and printing press, to Europe.
    </p>
  </div> 
  <div class="col-4">
    <h1 class="intro-card-title"><i class="fab fa-angellist"></i>News</h1>
  </div>
</div>
<!--some text finish-->
  <div  class="row">
    @foreach ($news as $new)
    <div class="col-5">
      <div class="card card-news">
       <h3 class="card-news-title">{{$new->title1}}</h3>
       <img class="card-news-img" src="{{$new->img2}}">
       <h6 class="card-news-author"><small>Author:{{$new->author}}</small></h6>
       <a class="card-news-link" href="{{route('news.show', $new->id)}}"> Read news case</a>
       <h6 class="card-news-date"><small>Added at:{{$new->created_at}}</small></h6>
      </div>
    </div>
    @endforeach
  </div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/cef03e2529.js" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

resources/views/accounts/layouts/header.blade.php
<div class="header">
<header>
<link rel="stylesheet" type="text/css" href="/css/main.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <ul class="navbar-nav">
      <li class="nav-item">
          <a class="navbar-brand" href="/accounts">
            <img src="https://istartblogging.com/wp-content/uploads/2016/03/absolut-logo-design-typography-300x62.png" class="d-inline-block align-top" alt="">
          </a>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="#">News</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Blogs</a>
      </li>
    </ul>
</nav>
</header>
<div>

resources/views/accounts/show.blade.php
<html>
<header>
<link rel="stylesheet" type="text/css" href="/css/main.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
<link rel="stylesheet" href="https://use.typekit.net/iul5qke.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/accounts">
    <img src="https://istartblogging.com/wp-content/uploads/2016/03/absolut-logo-design-typography-300x62.png" class="d-inline-block align-top" alt="">
  </a>
</nav>
</header>
<body>
<div class="container">
    <a class="arrow-go-back" href="/accounts"><i class="fas fa-arrow-left"></i></a>
<div class="row">
 <div class="col-sm-6">
    <h1 class="blog-page-title">{{$account->first_name}} {{$account->last_name}}</h1>
    <img class="blog-page-main-img" src="{{$account->avatarlink}}">
</div>
<div class="col-6">
<div class="card blog-page-contact-card">
   <h2> Info</h2>
    <h3>Email: <a href="#">{{$account->email}}</a></h3>
    <h3>City: {{$account->city}}</h3>
    <h3>Country: {{$account->country}}</h3>
</div>
<img class="blog-page-secondary-img" src="{{$account->blogimage1}}">
</div>
</div>
<div class="card blog-page-card-presentation">
    <h2 class="blog-page-card-presentation-title"> Job: {{$account->job_title}}</h4>
    <h4 class="blog-page-card-presentation-text"> Job descrip: {{$account->job_text}}</h4>
    <h4 class="blog-page-card-presentation-pres"> Presentation : <br>{{$account->presentation}}</h4>
    <img src="{{$account->blogimage2}}">
</div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

resources/views/news/show.blade.php
<html>
<header>
<link rel="stylesheet" type="text/css" href="/css/main.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
<link rel="stylesheet" href="https://use.typekit.net/iul5qke.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/accounts">
    <img src="https://istartblogging.com/wp-content/uploads/2016/03/absolut-logo-design-typography-300x62.png" class="d-inline-block align-top" alt="">
  </a>
</nav>
</header>
<body>
<div class="container">
    <a class="arrow-go-back" href="/accounts"><i class="fas fa-arrow-left"></i></a>
      <div class="card news-page-card">
        <h1 class="news-page-card-title">"{{$news->title1}}" <br> <small> {{$news->author}}</small></h1>
        <div class="row">
        <div  class="col-5 offset-1">
        <h5 class="news-page-card-text">{{$news->text1}}</h5>
      </div>
      <div  class="col-6">
          <img class="news-page-card-img" src="{{$news->img1}}">
        </div>
      </div >
      <h3 class="news-page-card-subt">{{$news->title2}}</h3> <br>
      <div class="row">
        <div class="col-6">
        <img class="news-page-card-img" src="{{$news->img2}}">
      </div>
      <div class="col-5 offset-1">
        <h5 class="news-page-card-text">{{$news->text2}}</h5>
      </div>
      </div>
      </div>
    </div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>